# Generated by Django 4.2.1 on 2024-04-24 14:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id_api', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, help_text='Brief description of the API', max_length=100)),
                ('terms_of_use', models.TextField(blank=True, help_text='Terms and conditions for API usage', verbose_name='Terms of Use')),
                ('logo', models.ImageField(null=True, upload_to='assets/images/', verbose_name='Logo')),
                ('visibility', models.BooleanField(default=False, null=True, verbose_name='Visibility')),
                ('website', models.TextField(blank=True, help_text='Base link for API ', verbose_name='Web Site')),
            ],
        ),
        migrations.CreateModel(
            name='APIcategory',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='APIForum',
            fields=[
                ('id_forum', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mapi.api')),
            ],
        ),
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('id_consommateur', models.AutoField(primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Functionnality',
            fields=[
                ('id_funct', models.AutoField(primary_key=True, serialize=False)),
                ('functName', models.CharField(max_length=100)),
                ('funct_descrip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id_tarif', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('api_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mapi.api')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mapi.consommateur')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id_thread', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mapi.consommateur')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mapi.apiforum')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint_parameter',
            fields=[
                ('id_parameter', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.type')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mapi.thread')),
            ],
        ),
        migrations.CreateModel(
            name='APIversion',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('num_version', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Stable', 'Stable'), ('Deprecated', 'Deprecated'), ('Obsolete', 'Obsolete')], max_length=50)),
                ('date_version', models.DateField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api')),
                ('functions', models.ManyToManyField(to='api_mapi.functionnality')),
            ],
        ),
        migrations.CreateModel(
            name='APIendpoint',
            fields=[
                ('id_endpoint', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=20, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.apiversion')),
            ],
        ),
        migrations.CreateModel(
            name='APIdocumentation',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('apiVersion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.apiversion')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Category', to='api_mapi.apicategory'),
        ),
        migrations.AddField(
            model_name='api',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.fournisseur', verbose_name='Provider'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id_subscription', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.consommateur')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.tarification')),
            ],
        ),
    ]
