# Generated by Django 5.0.3 on 2024-05-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiversion",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
