# Generated by Django 5.0.5 on 2024-05-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetarif',
            name='stripeId',
            field=models.CharField(default='id', max_length=50),
            preserve_default=False,
        ),
    ]
