# Generated by Django 4.2.1 on 2024-05-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiheader',
            name='type_id',
        ),
        migrations.AddField(
            model_name='apiqueryparam',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
