# Generated by Django 5.0.3 on 2024-05-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarification",
            name="quota_type",
        ),
    ]
