# Generated by Django 5.0.2 on 2024-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('AdminEmail', models.CharField(max_length=100)),
                ('AdminUsername', models.CharField(max_length=100)),
                ('AdminPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
