# Generated by Django 4.2.1 on 2024-06-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarification',
            name='rate_limit',
            field=models.IntegerField(null=True),
        ),
    ]
