# Generated by Django 4.2.1 on 2024-05-06 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiforum',
            name='api_id',
        ),
        migrations.AddField(
            model_name='api',
            name='forum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.apiforum', verbose_name='Forum'),
            preserve_default=False,
        ),
    ]
