# Generated by Django 5.0.2 on 2024-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiendpoint',
            name='externalDocDescription',
        ),
        migrations.RemoveField(
            model_name='apiendpoint',
            name='externalDocURL',
        ),
        migrations.AlterField(
            model_name='apiversion',
            name='base_links',
            field=models.ManyToManyField(null=True, to='api_mapi.baselink', verbose_name='Base Links'),
        ),
    ]
