# Generated by Django 5.0.2 on 2024-04-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='FRpassword',
        ),
    ]
