# Generated by Django 4.2.1 on 2024-04-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0002_rename_title_apiforum_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('api_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mapi.api')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_mapi.consommateur')),
            ],
        ),
    ]
