# Generated by Django 5.0.3 on 2024-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0002_alter_apiversion_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarification",
            name="rate_limit",
            field=models.IntegerField(null=True),
        ),
    ]
