# Generated by Django 5.0.3 on 2024-05-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0002_consommateur_cn_first_name_consommateur_cn_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consommateur',
            name='CN_first_name',
        ),
        migrations.RemoveField(
            model_name='consommateur',
            name='CN_last_name',
        ),
        migrations.RemoveField(
            model_name='consommateur',
            name='CNemail',
        ),
        migrations.RemoveField(
            model_name='consommateur',
            name='CNpassword',
        ),
        migrations.RemoveField(
            model_name='consommateur',
            name='CNphone',
        ),
        migrations.RemoveField(
            model_name='consommateur',
            name='CNstatus',
        ),
        migrations.RemoveField(
            model_name='consommateur',
            name='CNusername',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='FR_first_name',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='FR_last_name',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='FRemail',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='FRpassword',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='FRphone',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='FRstatus',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='FRusername',
        ),
    ]
