# Generated by Django 5.0.2 on 2024-05-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0002_remove_apiendpoint_externaldocdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint_parameter',
            name='id_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.apiendpoint'),
        ),
        migrations.AlterField(
            model_name='responseexample',
            name='id_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.apiendpoint'),
        ),
    ]
