# Generated by Django 5.0.2 on 2024-03-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('CN_first_name', models.CharField(max_length=100)),
                ('CN_last_name', models.CharField(max_length=100)),
                ('CNemail', models.CharField(max_length=100)),
                ('CNusername', models.CharField(max_length=100)),
                ('CNpassword', models.CharField(max_length=100)),
                ('CNphone', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='email',
            new_name='FR_first_name',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='first_name',
            new_name='FR_last_name',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='last_name',
            new_name='FRemail',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='password',
            new_name='FRpassword',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='phone',
            new_name='FRphone',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='username',
            new_name='FRusername',
        ),
    ]
