# Generated by Django 5.0.5 on 2024-05-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0002_typetarif_stripeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typetarif',
            name='stripeId',
        ),
        migrations.AddField(
            model_name='tarification',
            name='priceId',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
