# Generated by Django 4.2.1 on 2024-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0002_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
