# Generated by Django 4.2.1 on 2024-05-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0002_remove_apiheader_type_id_apiqueryparam_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(default='ended', max_length=20),
        ),
        migrations.AddField(
            model_name='tarification',
            name='priceId',
            field=models.CharField(default='price_1PDneKEwLPoE4RaHXfQcbdpj', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='rate_limit',
            field=models.IntegerField(),
        ),
    ]
