# Generated by Django 5.0.3 on 2024-05-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0002_remove_tarification_quota_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiendpoint",
            name="externalDocDescription",
        ),
        migrations.RemoveField(
            model_name="apiendpoint",
            name="externalDocURL",
        ),
    ]
