# Generated by Django 5.0.2 on 2024-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0002_remove_fournisseur_frpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
