# Generated by Django 5.0.3 on 2024-05-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0003_remove_apiendpoint_externaldocdescription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint_parameter",
            name="id_endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.apiendpoint",
            ),
        ),
    ]
