# Generated by Django 5.0.3 on 2024-05-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0003_alter_tarification_rate_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiendpoint",
            name="path",
            field=models.TextField(default="/"),
        ),
    ]
