# Generated by Django 5.0.5 on 2024-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0003_remove_typetarif_stripeid_tarification_priceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(default='active', max_length=20),
            preserve_default=False,
        ),
    ]
