# Generated by Django 4.2.1 on 2024-05-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0003_alter_thread_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiforum',
            old_name='api',
            new_name='api_id',
        ),
    ]
