# Generated by Django 5.0.2 on 2024-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0003_alter_fournisseur_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consommateur',
            name='CNpassword',
        ),
        migrations.AlterField(
            model_name='consommateur',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
