# Generated by Django 5.0.2 on 2024-03-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0003_consommateur_rename_email_fournisseur_fr_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIcategory',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Functionnality',
            fields=[
                ('id_funct', models.AutoField(primary_key=True, serialize=False)),
                ('functName', models.CharField(max_length=100)),
                ('funct_descrip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id_tarif', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id_api', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.fournisseur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.apicategory')),
                ('pricingPlans', models.ManyToManyField(to='api_mapi.tarification')),
            ],
        ),
        migrations.CreateModel(
            name='APIversion',
            fields=[
                ('id_version', models.AutoField(primary_key=True, serialize=False)),
                ('num_version', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Alpha', 'Alpha'), ('Beta', 'Beta'), ('Stable', 'Stable'), ('Deprecated', 'Deprecated'), ('Obsolete', 'Obsolete')], max_length=50)),
                ('date_version', models.DateField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api')),
                ('functions', models.ManyToManyField(to='api_mapi.functionnality')),
            ],
        ),
        migrations.CreateModel(
            name='APIendpoint',
            fields=[
                ('id_endpoint', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=20)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.apiversion')),
            ],
        ),
        migrations.CreateModel(
            name='APIdocumentation',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('apiVersion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.apiversion')),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id_subscription', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.consommateur')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.tarification')),
            ],
        ),
    ]
