# Generated by Django 5.0.2 on 2024-05-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0003_alter_endpoint_parameter_id_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiversion',
            name='base_links',
            field=models.ManyToManyField(blank=True, to='api_mapi.baselink', verbose_name='Base Links'),
        ),
    ]
