# Generated by Django 5.0.2 on 2024-05-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0004_alter_apiversion_base_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiversion',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
