# Generated by Django 5.0.2 on 2024-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0004_remove_consommateur_cnpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='FRemail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
