# Generated by Django 5.0.3 on 2024-05-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0004_alter_endpoint_parameter_id_endpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responseexample",
            name="id_endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.apiendpoint",
            ),
        ),
    ]
