# Generated by Django 4.2.1 on 2024-05-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0004_alter_pricingmodel_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='invoice',
            field=models.TextField(default='unavailable'),
            preserve_default=False,
        ),
    ]
