# Generated by Django 5.0.3 on 2024-05-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0004_apiendpoint_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiheader",
            name="type_id",
        ),
    ]
