# Generated by Django 5.0.2 on 2024-03-06 20:40

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0004_apicategory_functionnality_tarification_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoint',
            name='method',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=6, null=True),
        ),
    ]
