# Generated by Django 5.0.3 on 2024-05-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0005_remove_apiheader_type_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiqueryparam",
            name="required",
            field=models.BooleanField(default=False),
        ),
    ]
