# Generated by Django 5.0.3 on 2024-05-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0005_alter_responseexample_id_endpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarification",
            name="recommended",
        ),
    ]
