# Generated by Django 5.0.2 on 2024-05-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0005_apiversion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarification',
            name='quota_type',
        ),
    ]
