# Generated by Django 5.0.2 on 2024-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0005_alter_apiendpoint_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoint',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('POST', 'POST'), ('DELETE', 'DELETE')], max_length=20, null=True),
        ),
    ]
