# Generated by Django 5.0.2 on 2024-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0005_alter_fournisseur_fremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommateur',
            name='CNusername',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='FRusername',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
