# Generated by Django 5.0.2 on 2024-05-08 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0006_remove_tarification_quota_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingmodel',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api'),
        ),
        migrations.AlterField(
            model_name='pricingmodel',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the pricing model'),
        ),
        migrations.AlterField(
            model_name='pricingmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pricingmodel',
            name='period',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=100),
        ),
    ]
