# Generated by Django 5.0.3 on 2024-05-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0006_apiqueryparam_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiversion",
            name="base_links",
        ),
        migrations.DeleteModel(
            name="BaseLink",
        ),
    ]
