# Generated by Django 5.0.2 on 2024-05-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0007_alter_pricingmodel_api_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarification',
            name='recommended',
        ),
        migrations.AlterField(
            model_name='tarification',
            name='rate_limit',
            field=models.IntegerField(default=10000),
        ),
    ]
