# Generated by Django 5.0.3 on 2024-05-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0007_remove_apiversion_base_links_delete_baselink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiendpointbody",
            name="body_example",
            field=models.TextField(
                help_text="Example of a body", null=True, verbose_name="Example"
            ),
        ),
        migrations.AlterField(
            model_name="apiendpointbody",
            name="payload_description",
            field=models.TextField(
                help_text="Payload text", null=True, verbose_name="Payload text"
            ),
        ),
        migrations.AlterField(
            model_name="apiendpointbody",
            name="payload_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="apiheader",
            name="example_value",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="apiqueryparam",
            name="example_value",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="endpoint_parameter",
            name="example_value",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="responseexample",
            name="body",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="responseexample",
            name="code_status",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="responseexample",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
