# Generated by Django 5.0.3 on 2024-03-16 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0007_alter_admin_options_alter_consommateur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint_parameter',
            fields=[
                ('id_parameter', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.type')),
            ],
        ),
    ]
