# Generated by Django 5.0.3 on 2024-03-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0007_type_api_terme_of_use_endpoint_parameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api",
            name="terme_of_use",
        ),
    ]
