# Generated by Django 5.0.3 on 2024-06-06 23:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0008_alter_apiendpointbody_body_example_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("status_code", models.IntegerField()),
                ("response_time", models.FloatField()),
                ("endpoint", models.CharField(max_length=255)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_mapi.abonnement",
                    ),
                ),
            ],
        ),
    ]
