# Generated by Django 5.0.2 on 2024-05-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0008_remove_tarification_recommended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarification',
            name='rate_limit',
            field=models.IntegerField(null=True),
        ),
    ]
