# Generated by Django 5.0.3 on 2024-03-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0008_type_endpoint_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommateur',
            name='CNstatus',
            field=models.CharField(default='Active', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='FRstatus',
            field=models.CharField(default='Active', max_length=100),
            preserve_default=False,
        ),
    ]
