# Generated by Django 5.0.3 on 2024-03-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0008_alter_admin_options_alter_consommateur_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommateur',
            name='CNemail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
