# Generated by Django 5.0.3 on 2024-03-14 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0009_remove_api_api_name_remove_api_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="api_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="api",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.apicategory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="api",
            name="description",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="api",
            name="pricingPlans",
            field=models.ManyToManyField(to="api_mapi.tarification"),
        ),
        migrations.AddField(
            model_name="api",
            name="provider",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.fournisseur",
            ),
            preserve_default=False,
        ),
    ]
