# Generated by Django 5.0.3 on 2024-03-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0009_consommateur_cnstatus_fournisseur_frstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consommateur',
            old_name='id_fournisseur',
            new_name='id_consommateur',
        ),
    ]
