# Generated by Django 5.0.3 on 2024-03-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0009_alter_consommateur_cnemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consommateur',
            old_name='id_fournisseur',
            new_name='id_consommateur',
        ),
    ]
