# Generated by Django 5.0.3 on 2024-06-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0009_apiusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="quota_remaining",
            field=models.IntegerField(default=0),
        ),
    ]
