# Generated by Django 5.0.3 on 2024-03-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0010_rename_id_fournisseur_consommateur_id_consommateur'),
    ]

    operations = [
       
        
        migrations.AlterField(
            model_name='api',
            name='api_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Category', to='api_mapi.apicategory'),
        ),
        migrations.AlterField(
            model_name='api',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the API', max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.fournisseur', verbose_name='Provider'),
        ),
    ]
