# Generated by Django 5.0.3 on 2024-03-14 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0010_api_api_name_api_category_api_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api",
            name="pricingPlans",
        ),
        migrations.AddField(
            model_name="api",
            name="base_link",
            field=models.TextField(
                default="",
                help_text="Base link for API endpoints",
                verbose_name="Base Link",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="api",
            name="logo",
            field=models.ImageField(
                default="", upload_to="assets/images/", verbose_name="Logo"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="api",
            name="pricing_plans",
            field=models.ManyToManyField(
                to="api_mapi.tarification", verbose_name="Pricing Plans"
            ),
        ),
        migrations.AddField(
            model_name="api",
            name="terms_of_use",
            field=models.TextField(
                default="",
                help_text="Terms and conditions for API usage",
                verbose_name="Terms of Use",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="api",
            name="visibility",
            field=models.BooleanField(default=False, verbose_name="Visibility"),
        ),
        migrations.AlterField(
            model_name="api",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.apicategory",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="description",
            field=models.CharField(
                help_text="Brief description of the API", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="api",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.fournisseur",
                verbose_name="Provider",
            ),
        ),
    ]
