# Generated by Django 5.0.3 on 2024-06-11 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0010_abonnement_quota_remaining"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiusage",
            name="endpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.apiendpoint",
            ),
        ),
    ]
