# Generated by Django 5.0.3 on 2024-06-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0011_alter_apiusage_endpoint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiendpointbody",
            name="payload_description",
        ),
        migrations.RemoveField(
            model_name="apiendpointbody",
            name="payload_name",
        ),
    ]
