# Generated by Django 5.0.3 on 2024-03-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0012_remove_api_pricing_plans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="functionnality",
            name="funct_descrip",
        ),
    ]
