# Generated by Django 5.0.3 on 2024-03-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0012_remove_api_pricingplans_api_logo_api_terms_of_use_and_more'),
    ]

    operations = [
       
    ]
