# Generated by Django 5.0.2 on 2024-03-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0012_remove_api_pricing_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Category', to='api_mapi.apicategory'),
        ),
    ]
