# Generated by Django 4.2.1 on 2024-06-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0012_remove_apiendpointbody_payload_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidocumentation',
            name='apiVersion',
        ),
        migrations.AddField(
            model_name='apidocumentation',
            name='api_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_mapi.api', verbose_name='API'),
        ),
        migrations.AddField(
            model_name='apidocumentation',
            name='swagger_spec',
            field=models.TextField(blank=True),
        ),
    ]
