# Generated by Django 5.0.3 on 2024-03-20 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0013_remove_functionnality_funct_descrip"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiendpoint",
            name="description",
            field=models.TextField(
                default="", help_text="Brief description of the endPoint"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="externalDocDescription",
            field=models.TextField(
                default="", help_text="Brief label for external link"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="externalDocURL",
            field=models.TextField(
                default="", help_text="External link to more information"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ApiHeader",
            fields=[
                ("id_header", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("required", models.BooleanField(default=False)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="api_mapi.apiendpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApiQueryParam",
            fields=[
                ("id_queryparams", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_params",
                        to="api_mapi.apiendpoint",
                    ),
                ),
            ],
        ),
    ]
