# Generated by Django 5.0.2 on 2024-03-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0013_alter_api_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='base_link',
        ),
        migrations.AddField(
            model_name='api',
            name='website',
            field=models.TextField(blank=True, help_text='Base link for API ', verbose_name='Web Site'),
        ),
        migrations.AlterField(
            model_name='api',
            name='api_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Category', to='api_mapi.apicategory'),
        ),
        migrations.AlterField(
            model_name='api',
            name='description',
            field=models.CharField(blank=True, help_text='Brief description of the API', max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='logo',
            field=models.ImageField(null=True, upload_to='assets/images/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='api',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.fournisseur', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='api',
            name='terms_of_use',
            field=models.TextField(blank=True, help_text='Terms and conditions for API usage', verbose_name='Terms of Use'),
        ),
        migrations.AlterField(
            model_name='api',
            name='visibility',
            field=models.BooleanField(default=False, null=True, verbose_name='Visibility'),
        ),
    ]
