# Generated by Django 5.0.2 on 2024-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0014_remove_api_base_link_api_website_alter_api_api_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiversion',
            name='current',
            field=models.BooleanField(default=False, null=True, verbose_name='Current Version'),
        ),
    ]
