# Generated by Django 5.0.3 on 2024-03-20 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0014_apiendpoint_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiheader",
            name="type_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apiqueryparam",
            name="type_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.type",
            ),
        ),
        migrations.AlterField(
            model_name="endpoint_parameter",
            name="type_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.type",
            ),
        ),
    ]
