# Generated by Django 5.0.3 on 2024-03-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0015_apiheader_type_id_apiqueryparam_type_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiheader",
            name="value",
        ),
        migrations.RemoveField(
            model_name="apiqueryparam",
            name="value",
        ),
        migrations.AddField(
            model_name="apiheader",
            name="example_value",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apiqueryparam",
            name="example_value",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
