# Generated by Django 5.0.2 on 2024-04-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0015_apiversion_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiversion',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_mapi.api'),
        ),
        migrations.AlterField(
            model_name='apiversion',
            name='functions',
            field=models.ManyToManyField(null=True, to='api_mapi.functionnality'),
        ),
        migrations.AlterField(
            model_name='apiversion',
            name='num_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
