# Generated by Django 5.0.3 on 2024-03-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0016_remove_apiheader_value_remove_apiqueryparam_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiEndpointBody",
            fields=[
                ("id_body", models.AutoField(primary_key=True, serialize=False)),
                ("media_type", models.CharField(max_length=255)),
                ("payload_name", models.CharField(max_length=255)),
                (
                    "payload_description",
                    models.TextField(
                        help_text="Payload text", verbose_name="Payload text"
                    ),
                ),
                (
                    "body_example",
                    models.TextField(
                        help_text="Example of a body", verbose_name="Example"
                    ),
                ),
            ],
        ),
    ]
