# Generated by Django 5.0.3 on 2024-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0018_apiendpointbody_endpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseLink",
            fields=[
                ("baselink_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "url",
                    models.TextField(
                        help_text="Base link for API endpoints",
                        verbose_name="Base Link URL",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="api",
            name="base_link",
        ),
        migrations.AddField(
            model_name="api",
            name="website",
            field=models.URLField(
                default="", help_text="API website", verbose_name="Website"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="api",
            name="base_links",
            field=models.ManyToManyField(
                to="api_mapi.baselink", verbose_name="Base Links"
            ),
        ),
    ]
