# Generated by Django 5.0.3 on 2024-03-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0019_baselink_remove_api_base_link_api_website_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="api",
            name="base_links",
        ),
        migrations.AddField(
            model_name="apiversion",
            name="base_links",
            field=models.ManyToManyField(
                to="api_mapi.baselink", verbose_name="Base Links"
            ),
        ),
    ]
