# Generated by Django 5.0.3 on 2024-03-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0020_remove_api_base_links_apiversion_base_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiendpoint",
            name="api",
        ),
        migrations.AddField(
            model_name="endpoint_parameter",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="endpoint_parameter",
            name="required",
            field=models.BooleanField(default=False),
        ),
    ]
