# Generated by Django 5.0.3 on 2024-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0023_pricingmodel_typetarif_rename_type_typeparam_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingmodel",
            name="period",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Monthly", "Monthly"),
                    ("Yearly", "Yearly"),
                ],
                max_length=100,
            ),
        ),
    ]
