# Generated by Django 5.0.3 on 2024-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mapi', '0023_remove_api_pricingplans_api_logo_api_terms_of_use_and_more'),
    ]

    operations = [
        
    ]
