# Generated by Django 5.0.3 on 2024-04-04 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0024_alter_pricingmodel_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingmodel",
            name="id_api",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.api",
            ),
            preserve_default=False,
        ),
    ]
