# Generated by Django 5.0.3 on 2024-04-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0026_remove_tarification_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarification",
            old_name="apiVersion",
            new_name="pricingModel_id",
        ),
    ]
