# Generated by Django 5.0.3 on 2024-04-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0027_rename_apiversion_tarification_pricingmodel_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarification",
            old_name="pricingModel_id",
            new_name="pricingModel",
        ),
        migrations.RemoveField(
            model_name="pricingmodel",
            name="id_api",
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="api",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_mapi.api",
            ),
            preserve_default=False,
        ),
    ]
