# Generated by Django 5.0.3 on 2024-04-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_mapi", "0028_rename_pricingmodel_id_tarification_pricingmodel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarification",
            old_name="id_type",
            new_name="type",
        ),
    ]
